[helpers]

[default]
depends = []

[default.files]
"config/fish/config.fish" = "~/.config/fish/config.fish"
"config/niri/config.kdl" = "~/.config/niri/config.kdl"
"config/nvim" = "~/.config/nvim"
"config/nvim/vim/init.vim" = "~/.config/vim/vimrc"
"local/bin/program_search.sh" = "~/.local/bin/program_search.sh"
"local/bin/open_terminal_here.sh" = "~/.local/bin/open_terminal_here.sh"

[default.variables]

[settings]
default_target_type = "automatic"
