[helpers]

[default]
depends = []

[default.files]
"config/fish/config.fish" = "~/.config/fish/config.fish"
"local/bin/program_search.sh" = "~/.local/bin/program_search.sh"

[default.variables]

[settings]
default_target_type = "automatic"
