[helpers]

[default]
depends = []

[default.files]
"local/bin/" = "~/.local/bin/"
"config/fish/" = "~/.config/fish/"
"config/nvim/" = "~/.config/nvim/"
"config/vim/vimrc" = "~/.config/vim/vimrc"
"config/niri/config.kdl" = "~/.config/niri/config.kdl"
"config/alacritty/alacritty.toml" = "~/.config/alacritty/alacritty.toml"

[default.variables]

[settings]
default_target_type = "automatic"
